issues:
  - id: 1
    title: 'Dependencia de Datos Estáticos para el Talento'
    description: 'Actualmente, la información de artistas y obras reside en archivos .ts locales dentro de /src/data/, lo que requiere un nuevo despliegue cada vez que se une un talento.'
    argument: 'Esto limita la agilidad editorial y hace que el contenido se vuelva obsoleto rápidamente si la comunidad crece.'
    solution: 'Integrar un Headless CMS como Sanity o Storyblok para permitir que los administradores actualicen perfiles sin tocar el código.'
    labels: ['enhancement', 'needs-triage']
  - id: 2
    title: 'Ausencia de un Sistema de Autenticación'
    description: 'El proyecto no cuenta con una pasarela de inicio de sesión para que los talentos gestionen sus propios perfiles.'
    argument: 'La falta de autogestión sobrecarga a los desarrolladores y limita la interacción personalizada del usuario.'
    solution: 'Implementar Clerk para una configuración rápida de perfiles o Auth.js si se prefiere una solución de código abierto y flexible.'
    labels: ['enhancement', 'needs-triage']
  - id: 3
    title: 'Inexistencia de una Base de Datos Relacional Escalable'
    description: 'El almacenamiento de datos en archivos JSON o TS impide realizar consultas complejas, como filtrar talentos por múltiples habilidades simultáneamente.'
    argument: 'A medida que la base de datos de "Revolución Digital" crezca, los archivos estáticos afectarán el tiempo de compilación y la memoria.'
    solution: 'Adoptar Supabase (PostgreSQL) para manejar relaciones complejas entre talentos, categorías y colaboraciones con alto rendimiento.'
    labels: ['enhancement', 'needs-triage']
  - id: 4
    title: 'Vulnerabilidad ante Ataques XSS por falta de CSP'
    description: 'No se ha configurado explícitamente una Política de Seguridad de Contenido (CSP) en el proyecto.'
    argument: 'Al ser una plataforma que mostrará contenido de diversos creadores, existe el riesgo de inyección de scripts maliciosos.'
    solution: 'Activar la funcionalidad experimental de CSP nativa en Astro 5.9+ y usar experimentalStaticHeaders para servir los hashes de seguridad desde Vercel.'
    labels: ['bug', 'needs-triage']
  - id: 5
    title: 'Gestión Ineficiente de Carga de Archivos'
    description: 'El proyecto no tiene un flujo definido para que los músicos o artistas suban sus obras directamente.'
    argument: 'Subir archivos pesados a través de funciones serverless puede causar tiempos de espera (timeouts) y costos elevados.'
    solution: 'Implementar el patrón de Presigned URLs para que los usuarios suban sus archivos directamente a un bucket de S3 o Supabase Storage, optimizando el rendimiento del backend.'
    labels: ['enhancement', 'needs-triage']
  - id: 6
    title: 'Limitación de Actualización de Contenido (SSG Puro)'
    description: 'Al usar Generación de Sitios Estáticos (SSG), los cambios en la galería dinámica no se reflejan hasta que termina un nuevo build de producción.'
    argument: 'Los concursos activos y nuevas colaboraciones requieren inmediatez que el SSG tradicional no ofrece por sí solo.'
    solution: 'Configurar Regeneración Estática Incremental (ISR) en el adaptador de Vercel para invalidar y reconstruir páginas específicas bajo demanda sin redeployar todo el sitio.'
    labels: ['enhancement', 'needs-triage']
  - id: 7
    title: 'Arquitectura de Carpetas con Baja Escalabilidad'
    description: 'La carpeta src/components mezcla componentes transversales con específicos de galerías y talentos.'
    argument: 'Una estructura plana genera caos visual y dificultad de mantenimiento a medida que se añaden nuevas funcionalidades como "Escritura" o "Código".'
    solution: 'Organizar los archivos siguiendo la "Arquitectura de Gritos" (Screaming Architecture) o agrupando por "Features" para que la estructura refleje el dominio del proyecto.'
    labels: ['refactor', 'needs-triage']
  - id: 8
    title: 'Falta de Monitoreo de Experiencia de Usuario Real (RUM)'
    description: 'El proyecto confía en métricas de laboratorio (Lighthouse) pero no mide cómo cargan las imágenes en los dispositivos reales de la comunidad en Cuba.'
    argument: 'Las condiciones de red variables en la región exigen optimizaciones basadas en datos de campo para evitar altas tasas de rebote.'
    solution: 'Integrar el componente @casoon/astro-webvitals para capturar métricas como LCP e INP de usuarios reales y enviarlas a un endpoint de análisis.'
    labels: ['enhancement', 'needs-triage']
  - id: 9
    title: 'Uso de Rutas de Importación Relativas Complejas'
    description: 'Se utilizan rutas como ../../components/gallery/ en los archivos de la galería.'
    argument: 'Esto aumenta la carga cognitiva del desarrollador y facilita errores al mover archivos de directorio.'
    solution: 'Configurar Alias de Rutas (@/*) en el archivo tsconfig.json para simplificar las importaciones y mejorar la legibilidad del código.'
    labels: ['enhancement', 'needs-triage']
  - id: 10
    title: 'Optimización Manual de Imágenes Estáticas'
    description: 'Las imágenes en src/assets/ se procesan pero el proyecto no aprovecha plenamente los servicios de optimización en el borde (Edge).'
    argument: 'Los portafolios de fotografía pesados pueden degradar drásticamente el Largest Contentful Paint (LCP) si no se sirven en formatos como AVIF de forma dinámica.'
    solution: 'Habilitar el imageService en el adaptador de Vercel para que las imágenes se redimensionen y optimicen automáticamente en el CDN.'
    labels: ['enhancement', 'needs-triage']
  - id: 11
    title: 'Buscador de Talentos Limitado al Lado del Cliente'
    description: 'El buscador actual en TalentsCards.tsx filtra sobre un array estático cargado en memoria.'
    argument: 'Si la comunidad llega a tener miles de talentos, descargar todo el JSON en el cliente afectará el rendimiento y el consumo de datos móviles.'
    solution: 'Migrar a búsqueda en el servidor (Server-side Search) utilizando API Routes de Astro y consultas Full-text search en PostgreSQL.'
    labels: ['enhancement', 'needs-triage']
  - id: 12
    title: 'Ausencia de Pruebas Automatizadas (Unitarias y E2E)'
    description: 'La documentación menciona "Testing Manual" pero no hay una suite de pruebas automatizada integrada en el CI/CD.'
    argument: 'Las refactorizaciones en componentes críticos como DinamycGallery pueden introducir errores visuales o lógicos sin que el equipo lo note.'
    solution: 'Implementar Vitest para lógica de negocio y Playwright para asegurar que las rutas críticas (como el registro de concursos) funcionen en todos los navegadores.'
    labels: ['enhancement', 'needs-triage']
  - id: 13
    title: 'Falta de Interactividad en Tiempo Real'
    description: 'Los concursos y colaboraciones no muestran actualizaciones instantáneas (ej. nuevas postulaciones) sin recargar la página.'
    argument: 'La naturaleza comunitaria de "Revolución Digital" se beneficia de la "presencia" y el feedback inmediato.'
    solution: 'Utilizar las capacidades de Realtime de Supabase para actualizar la UI de concursos automáticamente cuando se añaden nuevos registros a la base de datos.'
    labels: ['enhancement', 'needs-triage']
  - id: 14
    title: 'Uso Excesivo de React para Componentes Sencillos'
    description: 'Se utilizan islas de React para funcionalidades que podrían resolverse con JavaScript estándar o componentes de Astro.'
    argument: 'Cada isla de React añade peso al bundle de JavaScript, lo que ralentiza la interactividad en redes móviles lentas.'
    solution: 'Migrar componentes puramente visuales a componentes de Astro (.astro) y usar scripts de cliente para interactividad ligera, reservando React solo para estados complejos.'
    labels: ['enhancement', 'needs-triage']
  - id: 15
    title: 'Gestión Insegura de Variables de Entorno'
    description: 'Aunque se usan archivos .env, no hay una validación estricta de que las variables necesarias existan en el entorno de producción.'
    argument: 'Fallos en la conexión con futuras APIs o servicios de backend pueden causar errores 500 silenciosos si faltan llaves secretas.'
    solution: 'Utilizar astro:env para definir esquemas de variables de entorno con validación en tiempo de build y tipado estático.'
    labels: ['enhancement', 'needs-triage']
  - id: 16
    title: 'Navegación entre Páginas con Recarga Completa'
    description: 'El paso entre /galeria y /talentos provoca una recarga total del navegador, perdiendo el estado de la aplicación.'
    argument: 'Esto degrada la percepción de "aplicación moderna" y aumenta el consumo de recursos al recargar el header y footer.'
    solution: 'Implementar View Transitions de Astro para permitir transiciones fluidas y persistencia de elementos entre rutas sin la sobrecarga de una SPA completa.'
    labels: ['enhancement', 'needs-triage']
  - id: 17
    title: 'Falta de Localización e Internacionalización (i18n)'
    description: 'La plataforma está diseñada únicamente en español, limitando la visibilidad de los talentos ante empresas o colaboradores internacionales.'
    argument: 'Para cumplir la visión de "mostrar talento" a nivel global, el soporte multiidioma es fundamental.'
    solution: 'Configurar el sistema de enrutamiento i18n nativo de Astro para servir contenido en español e inglés mediante subdirectorios de URL.'
    labels: ['enhancement', 'needs-triage']
  - id: 18
    title: 'Componentes con Props no Tipadas Rigurosamente'
    description: 'Algunos componentes Astro podrían estar aceptando props sin una interfaz TypeScript definida, facilitando errores de desarrollo.'
    argument: 'En un proyecto colaborativo, la falta de contratos claros en los componentes aumenta el tiempo de integración.'
    solution: 'Forzar el uso de la interfaz Props en todos los componentes .astro y activar el modo strict en el archivo tsconfig.json.'
    labels: ['enhancement', 'needs-triage']
  - id: 19
    title: 'Riesgo de Cold Starts en Funciones Dinámicas'
    description: 'Al migrar a SSR para perfiles de usuario, las funciones serverless de Node.js podrían experimentar latencia en la primera carga.'
    argument: 'Un retraso de 1 segundo en cargar un perfil de talento puede ser la diferencia entre una contratación o un rebote.'
    solution: 'Evaluar el uso del Vercel Edge Runtime para tareas de renderizado ligero y autenticación, reduciendo los cold starts a menos de 5ms.'
    labels: ['enhancement', 'needs-triage']
  - id: 20
    title: 'Falta de una Estrategia de Caching de API'
    description: 'Si el componente de galería llama a una API externa en cada renderizado de servidor, se consumen recursos innecesarios.'
    argument: 'Esto puede llevar a exceder las cuotas de Vercel y generar costos inesperados por uso de CPU.'
    solution: 'Implementar cabeceras Cache-Control agresivas o usar la funcionalidad de Data Cache de Vercel para reutilizar respuestas de API entre múltiples visitas.'
    labels: ['enhancement', 'needs-triage']
