feature:
  - any: ['feat/*', 'feature/*']

bug:
  - any: ['fix/*', 'bug/*']

documentation:
  - any: ['docs/*']

refactor:
  - any: ['refactor/*']

style:
  - any: ['style/*']

chore:
  - any: ['chore/*']
